# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: the_messanger_dev

  username: rails_dev
  password: Qwerty1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: the_messanger_test

  username: rails_dev
  password: Qwerty1234
  host: localhost
  port: 5432

production:
  <<: *default
  database: the_messanger_production
  username: teambalancer
  password: <%= ENV['TEAMBALANCER_DATABASE_PASSWORD'] %>
